apiVersion: batch/v1
kind: Job
metadata:
  name: sparkoperator-init
  namespace: datamesh-spark-operator
  labels:
    app.kubernetes.io/name: sparkoperator
    app.kubernetes.io/version: v2.4.0-v1beta1
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sparkoperator
        app.kubernetes.io/version: v2.4.0-v1beta1
    spec:
      serviceAccountName: sparkoperator
      restartPolicy: Never
      containers:
        - name: main
          image: gcr.io/spark-operator/spark-operator:v2.4.0-v1beta1-latest
          imagePullPolicy: IfNotPresent
          # command: ["/usr/bin/gencerts.sh", "-p"]
          command: ["/usr/bin/gencerts.sh", "-p", "--namespace", "datamesh-spark-operator", "--service", "datamesh-spark-webhook"]