---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datamesh-demo-airflow-apps
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: datamesh-demo
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    repoURL: https://github.com/opendatahub-io-contrib/datamesh-platform.git
    path: deployment/airflow/kustomize/overlays/development
    targetRevision: datamesh-sso
    # plugin:
    #   name: argocd-vault-plugin-kustomize
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    # - CreateNamespace=true
    - Validate=true
    - ServerSideApply=true
  # dependencies:
  #   - name: datamesh-demo-common-apps
  #     namespace: openshift-gitops