kind: Deployment
apiVersion: apps/v1
metadata:
  name: airflow
  labels:
    app.kubernetes.io/part-of: airflow
    app.kubernetes.io/name: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
  template:
    metadata:
      labels:
        app: airflow
    spec:
      restartPolicy: Always
      initContainers:
        - name: wait-for-airflow-migrations
          mage: quay.io/os-c-data-mesh-poc/airflow
          # image: quay.io/osclimate/2.7.3-omdingest-1.4.1
          args:
            - airflow
            - db
            - migrate
          env:
            - name: AIRFLOW__CORE__EXECUTOR
              value: LocalExecutor
            - name: AIRFLOW__CORE__LOAD_EXAMPLES
              value: 'False'
            - name: DB_HOST
              value: airflow-postgresql
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: airflow-postgresql
                  key: postgresql-database
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: airflow-postgresql
                  key: postgresql-user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: airflow-postgresql
                  key: postgresql-password
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              value: 'postgresql://$(DB_USER):$(DB_PASS)@$(DB_HOST):5432/$(DB_NAME)'
            - name: AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION
              value: 'True'
            - name: AIRFLOW__API__AUTH_BACKENDS
              value: >-
                airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session
            - name: AIRFLOW__OPENMETADATA_AIRFLOW_APIS__DAG_GENERATED_CONFIGS
              value: /opt/airflow/dag_generated_configs
            - name: AIRFLOW__LINEAGE__BACKEND
              value: >-
                airflow_provider_openmetadata.lineage.backend.OpenMetadataLineageBackend
            - name: AIRFLOW__LINEAGE__AIRFLOW_SERVICE_NAME
              value: airflow
            - name: AIRFLOW__LINEAGE__AUTH_PROVIDER_TYPE
              value: openmetadata
            - name: AIRFLOW__LINEAGE__JWT_TOKEN
              value: >-
                eyJraWQiOiJHYjM4OWEtOWY3Ni1nZGpzLWE5MmotMDI0MmJrOTQzNTYiLCJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJvcGVuLW1ldGFkYXRhLm9yZ1wiIiwic3ViIjoiaW5nZXN0aW9uLWJvdCIsImVtYWlsIjoiaW5nZXN0aW9uLWJvdEBvcGVubWV0YWRhdGEub3JnIiwiaXNCb3QiOnRydWUsInRva2VuVHlwZSI6IkJPVCIsImlhdCI6MTcwNjkwNjAzMCwiZXhwIjpudWxsfQ.f9ob5Zzrv0IIerLwhk9cDZtU9ELAbBA94NJ-Zv0Sy84NuG8adlDyU92Q7UtWC2qyT86IclctGK5-pkI11_yhP47VAJJCMpvME1JZKNIGUrc1oJxURolFGxcF1hTFIBUx6mKOjAF66HS9NMEEZbHt8QOt3emJDTS3TMlFSGrIC2Qui9w8Bnio0LOswteBbMyitgRYZfQv1lKjfJyqOp34KgNoXkFuCD4XoX37mPW6e_SMzZOX9L3m5qaUM_dugkGQr2Dt8jAXaXR8kRDJ7BigD6hFp1Z2nB4r7KbuyJ-4fLHiR7rK_1zE90a1UYZtDZVOiYTKu201QrXq0H8ilczHfQ
            - name: AIRFLOW__LINEAGE__OPENMETADATA_API_ENDPOINT
              value: 'http://openmetadata.datamesh-demo.svc.cluster.local:8585/api'
            - name: AIRFLOW_CONN_S3
              value: 'aws://minioAdmin:minio1234@/?endpoint_url=http:%2F%2Fminio.datamesh-demo.svc.cluster.local:9000'
            - name: AIRFLOW_CONN_TRINO_CONNECTION
              value: 'trino://admin:@trino:8080/'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
        - name: deploydagsfroms3
          image: 'quay.io/osclimate/minioclient:1.6'
          env:
            - name: DEPLOYMENT_TYPE
              value: init
            - name: S3_BUCKET_URL
              valueFrom:
                secretKeyRef:
                  name: dag-deployment
                  key: s3-bucketurl
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: dag-deployment
                  key: s3-accesskey
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: dag-deployment
                  key: s3-secret_key
          resources: {}
          volumeMounts:
            - name: mcconfig
              mountPath: /.mc
            - name: dags-data
              mountPath: /opt/airflow/dags
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      terminationGracePeriodSeconds: 30
      securityContext: {}
      containers:
        - resources:
            limits:
              cpu: '2'
              memory: 4Gi
            requests:
              cpu: '2'
              memory: 4Gi
          terminationMessagePath: /dev/termination-log
          name: airflow-web
          env:
            - name: AIRFLOW__CORE__EXECUTOR
              value: LocalExecutor
            - name: AIRFLOW__LOGGING__LOGGING_LEVEL
              value: DEBUG
            - name: AIRFLOW__CORE__LOAD_EXAMPLES
              value: 'False'
            - name: CURL_CA_BUNDLE
            - name: DB_HOST
              value: airflow-postgresql
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: airflow-postgresql
                  key: postgresql-database
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: airflow-postgresql
                  key: postgresql-user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: airflow-postgresql
                  key: postgresql-password
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              value: 'postgresql://$(DB_USER):$(DB_PASS)@$(DB_HOST):5432/$(DB_NAME)'
            - name: AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION
              value: 'True'
            - name: AIRFLOW__API__AUTH_BACKENDS
              value: >-
                airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session
            - name: AIRFLOW__OPENMETADATA_AIRFLOW_APIS__DAG_GENERATED_CONFIGS
              value: /opt/airflow/dag_generated_configs
            - name: AIRFLOW__LINEAGE__BACKEND
              value: >-
                airflow_provider_openmetadata.lineage.backend.OpenMetadataLineageBackend
            - name: AIRFLOW__LINEAGE__AIRFLOW_SERVICE_NAME
              value: airflow
            - name: AIRFLOW__LINEAGE__AUTH_PROVIDER_TYPE
              value: openmetadata
            - name: AIRFLOW__LINEAGE__JWT_TOKEN
              value: >-
                eyJraWQiOiJHYjM4OWEtOWY3Ni1nZGpzLWE5MmotMDI0MmJrOTQzNTYiLCJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJvcGVuLW1ldGFkYXRhLm9yZ1wiIiwic3ViIjoiaW5nZXN0aW9uLWJvdCIsImVtYWlsIjoiaW5nZXN0aW9uLWJvdEBvcGVubWV0YWRhdGEub3JnIiwiaXNCb3QiOnRydWUsInRva2VuVHlwZSI6IkJPVCIsImlhdCI6MTcwNjkwNjAzMCwiZXhwIjpudWxsfQ.f9ob5Zzrv0IIerLwhk9cDZtU9ELAbBA94NJ-Zv0Sy84NuG8adlDyU92Q7UtWC2qyT86IclctGK5-pkI11_yhP47VAJJCMpvME1JZKNIGUrc1oJxURolFGxcF1hTFIBUx6mKOjAF66HS9NMEEZbHt8QOt3emJDTS3TMlFSGrIC2Qui9w8Bnio0LOswteBbMyitgRYZfQv1lKjfJyqOp34KgNoXkFuCD4XoX37mPW6e_SMzZOX9L3m5qaUM_dugkGQr2Dt8jAXaXR8kRDJ7BigD6hFp1Z2nB4r7KbuyJ-4fLHiR7rK_1zE90a1UYZtDZVOiYTKu201QrXq0H8ilczHfQ
            - name: AIRFLOW__LINEAGE__OPENMETADATA_API_ENDPOINT
              value: 'http://openmetadata.datamesh-demo.svc.cluster.local:8585/api'
            - name: AIRFLOW_CONN_S3
              value: 'aws://minioAdmin:minio1234@/?endpoint_url=http:%2F%2Fminio.datamesh-demo.svc.cluster.local:9000'
            - name: AIRFLOW_CONN_TRINO_CONNECTION
              value: 'trino://admin:@trino:8080/'
            
            - name: AIRFLOW__WEBSERVER__WEB_SERVER_MASTER_TIMEOUT
              value: '300'
            - name: AIRFLOW__WEBSERVER__WORKER_REFRESH_BATCH_SIZE
              value: '0'
            - name: AIRFLOW__WEBSERVER__WORKER_REFRESH_INTERVAL
              value: '0'
            - name: AIRFLOW__WEBSERVER__RBAC
              value: 'False'
            - name: AIRFLOW__WEBSERVER__AUTHENTICATE
              value: 'False'
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: dags-data
              mountPath: /opt/airflow/dags
            - name: dags-generated-data
              mountPath: /opt/airflow/dag_generated_configs
            - name: dags-log
              mountPath: /opt/airflow/logs
          terminationMessagePolicy: File
          # image: quay.io/os-c-data-mesh-poc/airflow
          image: quay.io/osclimate/2.7.3-omdingest-1.4.1
          args:
            - bash
            - '-c'
            - exec airflow webserver ; airflow create_user --username airflow --lastname airflow --firstname jon --email airflow@apache.org --role Admin --password airflow 
        - resources:
            limits:
              cpu: '2'
              memory: 4Gi
            requests:
              cpu: '1'
              memory: 2Gi
          terminationMessagePath: /dev/termination-log
          name: scheduler
          env:
            - name: AIRFLOW__CORE__EXECUTOR
              value: LocalExecutor
            - name: AIRFLOW__CORE__LOAD_EXAMPLES
              value: 'False'
            - name: DB_HOST
              value: airflow-postgresql
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: airflow-postgresql
                  key: postgresql-database
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: airflow-postgresql
                  key: postgresql-user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: airflow-postgresql
                  key: postgresql-password
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              value: 'postgresql://$(DB_USER):$(DB_PASS)@$(DB_HOST):5432/$(DB_NAME)'
            - name: AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION
              value: 'True'
            - name: AIRFLOW__API__AUTH_BACKENDS
              value: >-
                airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session
            - name: AIRFLOW__OPENMETADATA_AIRFLOW_APIS__DAG_GENERATED_CONFIGS
              value: /opt/airflow/dag_generated_configs
            - name: AIRFLOW__LINEAGE__BACKEND
              value: >-
                airflow_provider_openmetadata.lineage.backend.OpenMetadataLineageBackend
            - name: AIRFLOW__LINEAGE__AIRFLOW_SERVICE_NAME
              value: airflow
            - name: AIRFLOW__LINEAGE__AUTH_PROVIDER_TYPE
              value: openmetadata
            - name: AIRFLOW__LINEAGE__JWT_TOKEN
              value: >-
                eyJraWQiOiJHYjM4OWEtOWY3Ni1nZGpzLWE5MmotMDI0MmJrOTQzNTYiLCJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJvcGVuLW1ldGFkYXRhLm9yZ1wiIiwic3ViIjoiaW5nZXN0aW9uLWJvdCIsImVtYWlsIjoiaW5nZXN0aW9uLWJvdEBvcGVubWV0YWRhdGEub3JnIiwiaXNCb3QiOnRydWUsInRva2VuVHlwZSI6IkJPVCIsImlhdCI6MTcwNjkwNjAzMCwiZXhwIjpudWxsfQ.f9ob5Zzrv0IIerLwhk9cDZtU9ELAbBA94NJ-Zv0Sy84NuG8adlDyU92Q7UtWC2qyT86IclctGK5-pkI11_yhP47VAJJCMpvME1JZKNIGUrc1oJxURolFGxcF1hTFIBUx6mKOjAF66HS9NMEEZbHt8QOt3emJDTS3TMlFSGrIC2Qui9w8Bnio0LOswteBbMyitgRYZfQv1lKjfJyqOp34KgNoXkFuCD4XoX37mPW6e_SMzZOX9L3m5qaUM_dugkGQr2Dt8jAXaXR8kRDJ7BigD6hFp1Z2nB4r7KbuyJ-4fLHiR7rK_1zE90a1UYZtDZVOiYTKu201QrXq0H8ilczHfQ
            - name: AIRFLOW__LINEAGE__OPENMETADATA_API_ENDPOINT
              value: 'http://openmetadata.datamesh-demo.svc.cluster.local:8585/api'
            - name: AIRFLOW_CONN_S3
              value: 'aws://minioAdmin:minio1234@/?endpoint_url=http:%2F%2Fminio.datamesh-demo.svc.cluster.local:9000'
            - name: AIRFLOW_CONN_TRINO_CONNECTION
              value: 'trino://admin:@trino.datamesh-demo.svc.cluster.local:8080/'
            - name: AIRFLOW__WEBSERVER__WEB_SERVER_MASTER_TIMEOUT
              value: '300'
            - name: AIRFLOW__WEBSERVER__WORKER_REFRESH_BATCH_SIZE
              value: '0'
            - name: AIRFLOW__WEBSERVER__WORKER_REFRESH_INTERVAL
              value: '0'
            - name: AIRFLOW__WEBSERVER__RBAC
              value: 'False'
            - name: AIRFLOW__WEBSERVER__AUTHENTICATE
              value: 'False'
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: dags-data
              mountPath: /opt/airflow/dags
            - name: dags-generated-data
              mountPath: /opt/airflow/dag_generated_configs
            - name: dags-log
              mountPath: /opt/airflow/logs
          terminationMessagePolicy: File
          # image: quay.io/os-c-data-mesh-poc/airflow
          image: quay.io/osclimate/2.7.3-omdingest-1.4.1
          args:
            - bash
            - '-c'
            - exec airflow scheduler
        - name: mc
          image: 'quay.io/osclimate/minioclient:1.6'
          env:
            - name: DEPLOYMENT_TYPE
              value: sidecar
            - name: S3_BUCKET_URL
              valueFrom:
                secretKeyRef:
                  name: dag-deployment
                  key: s3-bucketurl
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: dag-deployment
                  key: s3-accesskey
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: dag-deployment
                  key: s3-secret_key
          resources:
            limits:
              cpu: '2'
              memory: 4Gi
            requests:
              cpu: '1'
              memory: 2Gi
          volumeMounts:
            - name: mcconfig
              mountPath: /.mc
            - name: dags-data
              mountPath: /opt/airflow/dags
            - name: dags-log
              mountPath: /opt/airflow/logs
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      volumes:
        - name: dags-data
          emptyDir: {}
        - name: dags-generated-data
          emptyDir: {}
        - name: dags-log
          emptyDir: {}
        - name: config
          emptyDir: {}
        - name: mcconfig
          emptyDir: {}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%