kind: ConfigMap
apiVersion: v1
metadata:
  name: sso-env-config
data:
  # airflow-database-conn: 'postgresql://$(DB_USER):$(DB_PASS)@$(DB_HOST):5432/$(DB_NAME)'
  # airflow-core-dags-paused-at-creation: 'True'
  # airflow-api-auth-backends: 'airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session'
  # airflow-openmetadata-api-dag-generated-configs: '/opt/airflow/dag_generated_configs'
  # airflow-airflow-lineage-backwebd: 'airflow_provider_openmetadata.lineage.backend.OpenMetadataLineageBackend'
  # airflow-lineage-airflow-service: 'airflow'
  # airflow-lineage-auth-provider-type: 'openmetadata'
  # airflow-lineage-jwt-token: 'eyJraWQiOiJHYjM4OWEtOWY3Ni1nZGpzLWE5MmotMDI0MmJrOTQzNTYiLCJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9'
  # airflow-lineage-openmetadata-api-endpoint: 'http://openmetadata:8585/api'
  # airflow-lineage-conn-s3: 'aws://minioAdmin:minio1234@/?endpoint_url=http:%2F%2Fminio:9000'
  # airflow-conn-trino-connection: 'trino://admin:@trino:8080/'
  # api-base-url: 'https://keycloak.apps.osc-cl4.apps.$(NAMESPACE).org/realms/KeycloakRealm'
  # oauth-token-url: 'https://keycloak.apps.osc-cl4.apps.$(NAMESPACE).org/realms/KeycloakRealm/protocol/openid-connect/token'
  # oauth-authorize-url: 'https://keycloak.apps.osc-cl4.apps.$(NAMESPACE).org/realms/KeycloakRealm/protocol/openid-connect/auth'
  # oauth-user-info: 'https://keycloak.apps.osc-cl4.apps.$(NAMESPACE).org/realms/KeycloakRealm/protocol/openid-connect/userinfo'
  # oauth-logout-redirect-url: 'https://keycloak.apps.osc-cl4.apps.$(NAMESPACE).org/realms/KeycloakRealm/protocol/openid-connect/logout'
  # oauth-jwk-uri: 'https://keycloak.apps.osc-cl4.apps.$(NAMESPACE).org/realms/KeycloakRealm/protocol/openid-connect/certs'
  # client-id: 'airflow'
  # client-secret: 'NTI1hTfr8o0SAcAesblaeWN2kqfUiSA4'
  # odic-issuer: 'https://keycloak.apps.osc-cl4.apps.$(NAMESPACE).org/realms'
  # airflow-webserver-rbac: 'False'
  # airflow-webserver-authendicate: 'False'

  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql://$DB_USER:$DB_PASS@$DB_HOST:5432/$DB_NAME
  AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'True'
  AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session'
  AIRFLOW__OPENMETADATA_AIRFLOW_APIS__DAG_GENERATED_CONFIGS: '/opt/airflow/dag_generated_configs'
  AIRFLOW__LINEAGE__BACKEND: 'airflow_provider_openmetadata.lineage.backend.OpenMetadataLineageBackend'
  AIRFLOW__LINEAGE__AIRFLOW_SERVICE_NAME: 'airflow'
  AIRFLOW__LINEAGE__AUTH_PROVIDER_TYPE: 'openmetadata'
  AIRFLOW__LINEAGE__JWT_TOKEN: 'eyJraWQiOiJHYjM4OWEtOWY3Ni1nZGpzLWE5MmotMDI0MmJrOTQzNTYiLCJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJvcGVuLW1ldGFkYXRhLm9yZ1wiIiwic3ViIjoiaW5nZXN0aW9uLWJvdCIsImVtYWlsIjoiaW5nZXN0aW9uLWJvdEBvcGVubWV0YWRhdGEub3JnIiwiaXNCb3QiOnRydWUsInRva2VuVHlwZSI6IkJPVCIsImlhdCI6MTcwNjkwNjAzMCwiZXhwIjpudWxsfQ.f9ob5Zzrv0IIerLwhk9cDZtU9ELAbBA94NJ-Zv0Sy84NuG8adlDyU92Q7UtWC2qyT86IclctGK5-pkI11_yhP47VAJJCMpvME1JZKNIGUrc1oJxURolFGxcF1hTFIBUx6mKOjAF66HS9NMEEZbHt8QOt3emJDTS3TMlFSGrIC2Qui9w8Bnio0LOswteBbMyitgRYZfQv1lKjfJyqOp34KgNoXkFuCD4XoX37mPW6e_SMzZOX9L3m5qaUM_dugkGQr2Dt8jAXaXR8kRDJ7BigD6hFp1Z2nB4r7KbuyJ-4fLHiR7rK_1zE90a1UYZtDZVOiYTKu201QrXq0H8ilczHfQ'
  AIRFLOW__LINEAGE__OPENMETADATA_API_ENDPOINT: 'http://openmetadata:8585/api'
  AIRFLOW_CONN_S3: 'aws://minioAdmin:minio1234@/?endpoint_url=http:%2F%2Fminio:9000'
  AIRFLOW_CONN_TRINO_CONNECTION: 'trino://admin:@trino:8080/'
  OAUTH_TOKEN_URL: 'https://keycloak.$(NAMESPACE).apps.rosa-8grhg.ssnp.p1.openshiftapps.com/realms/KeycloakRealm/protocol/openid-connect/token'
  OAUTH_AUTHORIZE_URL: 'https://keycloak.$(NAMESPACE).apps.rosa-8grhg.ssnp.p1.openshiftapps.com/realms/KeycloakRealm/protocol/openid-connect/auth'
  OAUTH_USER_INFO: 'https://keycloak.$(NAMESPACE).apps.rosa-8grhg.ssnp.p1.openshiftapps.com/realms/KeycloakRealm/protocol/openid-connect/userinfo'
  OAUTH_LOGOUT_REDIRECT_URL: 'https://keycloak.$(NAMESPACE).apps.rosa-8grhg.ssnp.p1.openshiftapps.com/realms/KeycloakRealm/protocol/openid-connect/logout'
  OAUTH_JWKS_URI: 'https://keycloak.$(NAMESPACE).apps.rosa-8grhg.ssnp.p1.openshiftapps.com/realms/KeycloakRealm/protocol/openid-connect/certs'
  CLIENT_ID: 'airflow'
  CLIENT_SECRET: 'FZkGXczeCmde2G8cYIdB7Gfhx4RCNfWp'
  OIDC_ISSUER: 'https://keycloak-$(NAMESPACE).apps.rosa-8grhg.ssnp.p1.openshiftapps.com/realms/KeycloakRealm'
  AIRFLOW__WEBSERVER__RBAC: 'False'
  AIRFLOW__WEBSERVER__AUTHENTICATE: 'False'
  AIRFLOW__WEBSERVER__WEB_SERVER_MASTER_TIMEOUT: '300'
  AIRFLOW__WEBSERVER__WORKER_REFRESH_BATCH_SIZE: '0'
  AIRFLOW__WEBSERVER__WORKER_REFRESH_INTERVAL: '0'